Added simple game menu & created interface of game objects
Halaidzhy-Studio/Battle_Royale_Tanks pull request #7
Opened 2018-04-16 15:41 UTC by SinimaWath

Основные классы клиентской части игры. И игровое демо меню

2018-04-16 16:49 UTC, leshiy1295 commented on .gitignore
> +/Box2D/*
почему Вы решили не добавлять библиотеку в репозиторий?

2018-04-16 16:49 UTC, leshiy1295 commented on Battle-Royale-Tank.pro
> +    GameObjectsViews/tankview.cpp \
возможно, лучше использовать wildcard-выражения (вида *.cpp)

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/gamemenu.cpp
> +                 QApplication::desktop()->height()*0.90f);
магические константы

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/gameroom.h
> +    void setRoomName(const QString &roomName);
это не class, а struct, так как все геттеры/сеттеры тривиальные

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/gameroom.h
> +#include<QString>
отвяжите класс от Qt

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/multiplayermenu.cpp
> +    roomsCount = 2;
хардкод
лучше вынести в отдельное свойство

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/multiplayermenu.cpp
> +    // Download rooms to QVector<GameRoom>
лучше не оставлять нерабочий код в итоговом репозитории
иначе нужно оставить комментарий, почему этот участок остался

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/multiplayermenu.cpp
> +    delete ui;
лучше использовать умный указатель, чтобы об этом не думать

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/multiplayermenu.cpp
> +        for (qint16 i = 0; i < roomsList_.size(); ++i){
зачем тут qint16?
используйте auto и for-range конструкцию ИЛИ forEach из STL

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/roomlistelement.cpp
> +    qDebug() << __FUNCTION__ << "\n";
лучше вынести в отдельную сущность логгера

2018-04-16 16:49 UTC, leshiy1295 commented on GameMenu/roomlistelement.cpp
> +    gameRoom_ = gameRoom;
опять же - геттеры/сеттеры тривиальны => структура, а не класс

2018-04-16 16:49 UTC, leshiy1295 commented on gamescene.h
> +    b2World* b2GameWorld_;
жёсткая привязка к Box2D
название класса этого не отражает
лучше сделать в виде отдельной иерархии, где Box2D - одна из реализаций

2018-04-16 17:42 UTC, SinimaWath commented on .gitignore
> +/Box2D/*
Мне кажется, излишне 20к строчек кода хранить в репозитории

2018-04-18 18:05 UTC, SinimaWath commented on GameMenu/roomlistelement.cpp
> +    qDebug() << __FUNCTION__ << "\n";
А что такое сущность логерра? Специальный класс нужно писать?

2018-04-18 18:12 UTC, SinimaWath commented on gamescene.h
> +    b2World* b2GameWorld_;
Пока что не сильно понимаю. Добавил b2World, потому что у обьектов наследованных от QGraphicsScene есть метод/слот advance, который обноаляется состояние всех обьектов, которые он содержит. А сам b2World, имеет метод Step(), который обновляет состояние все объектов, находящихся на "физической" сцене движкк Box2D. Поэтому считаю, что хранить указатель на обьект движка целесобразно, так как выполняют одну функцию

2018-04-18 18:59 UTC, leshiy1295 commented on GameMenu/roomlistelement.cpp
> +    qDebug() << __FUNCTION__ << "\n";
да
движки разные бывают
плюс, бывает необходимо отправлять сразу логи в несколько систем

2018-04-18 19:02 UTC, leshiy1295 commented on gamescene.h
> +    b2World* b2GameWorld_;
тут речь не про функцию - так-то ясно, что box2d вызываться, вероятно должен.
Просто сейчас этот класс жёстко завязан на box2d. Лучше все эти зависимости выносить в отдельные сущности, то есть тут оставить всю необходимую логику, а где-нибудь в IMPL классе уже заиспользовать box2d, например, при этом опираясь опять же на указателе на интерфейс.
Сейчас же у Вас в header файле зависимость на box2d.

2018-04-19 15:06 UTC, SinimaWath commented on Battle-Royale-Tank.pro
> +    GameObjectsViews/tankview.cpp \
Исправил

2018-04-19 15:06 UTC, SinimaWath commented on .gitignore
> +/Box2D/*
Добавил

2018-04-19 15:07 UTC, SinimaWath commented on GameMenu/multiplayermenu.cpp
> +    delete ui;
Это сгенерированный код Qt, решил не трогать

2018-04-19 15:07 UTC, SinimaWath commented on GameMenu/multiplayermenu.cpp
> +        for (qint16 i = 0; i < roomsList_.size(); ++i){
Иправил

2018-04-19 15:09 UTC, SinimaWath commented on GameMenu/roomlistelement.cpp
> +    gameRoom_ = gameRoom;
Убрал геттеры и сеттеры. Если этот обьект явлется производным классом от виджета и имеет специфичные методы, его нужно делать структурой?

2018-04-19 16:18 UTC, SinimaWath commented on gamescene.h
> +    b2World* b2GameWorld_;
Сделал интерфейс для движка физики у которого есть метод update.

2018-04-30 20:35 UTC, leshiy1295 reviewed
Стоит указатели заменить на умные указатели, обычные массивы - на STL-контейнеры, вынести константы в конфигурационные файлы, которые подгружать на старте приложения.
Ну и реализовывать саму логику игры и сетевого взаимодействия... Сейчас могу поставить частичные баллы за первый модуль.

2018-04-30 20:35 UTC, leshiy1295 commented on GameMenu/multiplayermenu.cpp
> +        roomsList_.push_back(new GameRoom(str.toStdString(),static_cast<short int>(32), static_cast<short int>(2)));
что такое 32 и 2?
что такое roomsList_? Если это модельная сущность, то следует лучше вызывать метод модели, а не писать тут его реализацию...

2018-04-30 20:35 UTC, leshiy1295 commented on GameObjects/gamephysicsengineimpl.cpp
> +GamePhysicsEngineImpl::GamePhysicsEngineImpl(): velocityIteration_(6),
константы 2 и 6 - непонятно...

2018-04-30 20:35 UTC, leshiy1295 commented on GameObjectsViews/tankview.cpp
> +    painter->setPen(Qt::red);
возможно, стоит вынести для возможности кастомизации/задании тем/различении вражеских и дружественных танков, цвета в зависимости от мощности танка/его уровнем здоровья и др.

2018-04-30 20:35 UTC, leshiy1295 commented on main.cpp
> +#include <QApplication>
Хорошо, что добавили Box2D - если бы его закрыли, например, - теперь ваш проект всё равно будет жить :)
В целом, libBox2d.a - если подключили библиотеку, то достаточно добавить header-файлы, необходимые для корректной работы с ней. Но, с другой стороны, можно добавить и полностью все исходники для возможности дальнейшей поддержки и фикса багов. Так что тут - как удобнее - можно и так, и так! :)

2018-04-30 20:35 UTC, leshiy1295 commented on main.cpp
> +    QApplication a(argc, argv);
Лучше отделить и main от Qt - выделить всю часть за инициализацию игрового движка в отдельный класс-наследника от некоторого Application, а тут вызывать его... Также здесь можно будет добавить инициализацию логгера/сетевого соединения/ресурсной системы для работы с конфигурационными файлами и пр.
Выделение удобно, например, при тестировании - бывает, что необходимо подменять реализацию/добавлять новые тестовые функции, вплоть до методов создания приложения.

2018-04-30 20:35 UTC, leshiy1295 commented on packages.h
> +    TankDetails tanks[32]; // доп. информация о танках
почему 32?

2018-04-30 20:35 UTC, leshiy1295 commented on packages.h
> +    quint16 leftTopX; // координата X верхнего левого угла игровой области
почему quintX, а не size_t/int?

2018-05-07 22:44 UTC, SinimaWath commented
Полностью пересмотрел архитектуру приложения.
Каждый объект имеет метод update().

- Игровые объекты реализуют различные Компоненты. Обязательный компоненты для всех: ViewComponent ( отвечает за отображение данных ), PhysicsComponent ( отвечает за взаимодействие объектов в физ. мире ). Шаблон Component. Для создания взаимодествий между компонентами разных объектов, еще нужно написать Mediator(Manager) для каждого компонента ( в процессе). **Проблема** **: пока не знаю как должны быть устроены эти менеджеры и как их писать и где хранить.**
- Созданием объектов будут заниматься Строители и Директоры ( builders ). Для разных типов объекта будут свои Строители ( ConfigGameBuilder создает из конфига объект ).  **Проблема : На каком этапе создавать и инициализировать компоненты объекта ( Components ). Я считаю, что Строители и должны создавать компоненты и связи между ними, но тогда теряется гибкость. Не будет возможности легко заменить реализацию компонентов. Вторая идея: создавать и инициализировать компоненты в Директоре после создания Строителем объекта**
- GameData - интерфейс для работы с ресурсами. **Проблема :  в данный момент у меня абсолютно не гибкое решение. Не знаю как выйти из положения. Если думать наперед, то будет существовать слишком много структур ( InfoStruct ) для объектов. Вторая проблема: при загрузке из конфига в локальные структуры, слишком много лишнего кода проверок try catch.** Вопрос: как передавать эти структуры? Указатели, значение, ссылки. И стоит ли использовать умные указатели лишь для маленьких структур 
- Logger - по хорошему его нужно переписать на обычный класс. Пока что и так сойдет :)

2018-05-07 22:47 UTC, SinimaWath commented on packages.h
> +    TankDetails tanks[32]; // доп. информация о танках
Не мой класс. А Андрея

2018-05-07 22:48 UTC, SinimaWath commented on packages.h
> +    quint16 leftTopX; // координата X верхнего левого угла игровой области
Не мой класс, а Андрея.

2018-05-09 12:19 UTC, SinimaWath commented on main.cpp
> +    QApplication a(argc, argv);
Попытался это исправить. Класс engineQT

2018-05-13 09:47 UTC, leshiy1295 commented on packages.h
> +    quint16 leftTopX; // координата X верхнего левого угла игровой области
Как мне тогда это оценивать?
В каждой ветке должна быть индивидуальная работа, чтобы вас можно было оценивать независимо друг от друга

2018-05-13 10:07 UTC, leshiy1295 reviewed
кажется, что всё очень неплохо - Вы на правильном пути :)
Нужно продолжать в том же духе!

2018-05-13 10:07 UTC, leshiy1295 commented on GameMenu/gameroom.cpp
> +std::string GameRoom::roomName() const
это не class, а struct, так как все геттеры и сеттеры тривиальные
поэтому можно перенести их из private в public, если усложнение не планируется

2018-05-13 10:07 UTC, leshiy1295 commented on GameMenu/multiplayermenu.cpp
> +   // currentTankTypeNum_ = (currentTankTypeNum_ + 1) % tankTypeList_.size();
почему код закомментирован?

2018-05-13 10:07 UTC, leshiy1295 commented on builders/configtankbodybuilder.cpp
> +
нет реализации?

2018-05-13 10:07 UTC, leshiy1295 commented on main.cpp
> +    gameConfig->upload("/home/sinimawath/QtProjects/Battle-Royale-Tank/Resources/config.cfg");
путь до конфига стоит передавать через argv

2018-05-13 10:07 UTC, leshiy1295 commented on main.cpp
> +#include "utils/gamedata.h"
лишние include нужно убрать

2018-05-13 10:07 UTC, leshiy1295 commented on main.cpp
> +    std::shared_ptr<GameData> gameData = std::dynamic_pointer_cast<GameData>(gameConfig);
мне кажется, что нужно тут попросить фабрику (или хотя бы статический метод GameData) создать объект из конфига, переданному через Ваш абстрактный интерфейс

2018-05-13 10:07 UTC, leshiy1295 commented on objects/tankbody.h
> +    BodyInfoRect tankBodyInfo_; // ViewComponent + PhysicsComoponent
?

2018-05-13 10:07 UTC, leshiy1295 commented on utils/configgamedata.cpp
> +MenuWindowInfo ConfigGameData::getMenuWindowInfo()
Можно разбить получение конфигов на разные классы и делегировать им конструирование нужного - см. пример из последней лекции про делегированный полиморфизм - например, так, чтобы пользователь продолжал работать через ConfigGameData снаружи, но всё было не в одном файле...

2018-05-13 10:07 UTC, leshiy1295 commented on utils/configgamedata.cpp
> +    try{
try...catch можно вынести в отдельный метод по имени поля

2018-05-13 10:07 UTC, leshiy1295 commented on utils/logger.cpp
> +#include "logger.h"
ну да
лучше сделать интерфейс логгера абстрактным и просто всё это поместить в одну из его реализаций на Qt - сейчас он выглядит довольно скудно - возможно, что-то ещё можно в него вынести? Ведь надо работать с ним через базовый класс
выбирать ту или иную нужно фабрикой, например, при считывании конфигурационного файла

2018-05-13 10:43 UTC, SinimaWath commented on GameMenu/multiplayermenu.cpp
> +   // currentTankTypeNum_ = (currentTankTypeNum_ + 1) % tankTypeList_.size();
Черт, забыл. Нерабочий..

2018-05-13 10:45 UTC, SinimaWath commented on main.cpp
> +    gameConfig->upload("/home/sinimawath/QtProjects/Battle-Royale-Tank/Resources/config.cfg");
Попыта.сь сделать через qtresources. Путь будет задавать вот так ":Resources/config.cfg"

2018-05-13 10:45 UTC, SinimaWath commented on main.cpp
> +#include "utils/gamedata.h"
Хорошо

2018-05-13 10:47 UTC, SinimaWath commented on main.cpp
> +    std::shared_ptr<GameData> gameData = std::dynamic_pointer_cast<GameData>(gameConfig);
Подумаю и попробую

2018-05-13 10:48 UTC, SinimaWath commented on objects/tankbody.h
> +    BodyInfoRect tankBodyInfo_; // ViewComponent + PhysicsComoponent
Не рабочий код забыл. А так раньше было идея все информации хранить в классе контейнере TankBody и так далее. Ушел от этого, и теперь для каждого Объекта контейнара будет создаваться Менеджер класс, в след. коммите увидите

2018-05-13 10:50 UTC, SinimaWath commented on utils/configgamedata.cpp
> +MenuWindowInfo ConfigGameData::getMenuWindowInfo()
Хорошо, посмотрю.

2018-05-13 10:51 UTC, SinimaWath commented on utils/configgamedata.cpp
> +    try{
Вынес в отдельный шаблонный метод под название lookup(). Который и считывает все поля

2018-05-13 10:53 UTC, SinimaWath commented on utils/configgamedata.cpp
> +MenuWindowInfo ConfigGameData::getMenuWindowInfo()
А полученную информации из различных конфига хранить в структурах( ...InfoStruct )?

2018-05-13 15:51 UTC, SinimaWath commented on builders/configtankbodybuilder.cpp
> +
Пока что да

2018-05-13 20:32 UTC, SinimaWath commented on utils/logger.cpp
> +#include "logger.h"
Сделал

2018-05-13 20:34 UTC, SinimaWath commented
- Попытался исправить все замечания. 
- Начал писать компоненты, строителей и директоров для объектов.
- Внедрил делегированный полиформизм, пока что только для тех структур, которые используются
- написал фабричный метод для класса GameData
- логгер теперь обычный класс

2018-05-13 20:40 UTC, SinimaWath commented on packages.h
> +    quint16 leftTopX; // координата X верхнего левого угла игровой области
Удалил

2018-05-13 20:40 UTC, SinimaWath commented on GameMenu/gameroom.cpp
> +std::string GameRoom::roomName() const
Изменил в struct

2018-05-13 21:43 UTC, leshiy1295 requested changes

2018-05-13 21:43 UTC, leshiy1295 commented on utils/gamedata/configgamedata.h
> +#include <libconfig.h++>
следует убрать эту зависимость внутрь реализации

2018-05-13 21:43 UTC, leshiy1295 commented on utils/logger.h
> +    static void setLoggerDist(const std::string& dist);
как планируется вызывать эти методы, которых нет в общем интерфейсе?

2018-05-13 21:43 UTC, leshiy1295 commented on packages.h
> +    quint16 leftTopX; // координата X верхнего левого угла игровой области
но я всё ещё вижу этот класс тут...

2018-05-13 21:43 UTC, leshiy1295 commented on main.cpp
> +    std::shared_ptr<GameData> gameData = gameConfig->createGameData();
Всё же, на мой взгляд, конфиг - пассивный объект, основная задача которого - считать данные из файла и предоставлять их через обобщённый интерфейс клиентам. GameData должен уметь порождать себя сам, или эту ответственность стоит возложить на отдельную сущность, если таких разных Data много.
Но тут вроде бы достаточно просто добавить статический метод, принимающий конфиг.

2018-05-13 21:43 UTC, leshiy1295 commented on main.cpp
> +    std::shared_ptr<ConfigGameData> gameConfig(new ConfigGameData(logger));
Исходя из коммента ниже - тут стоит работать через базовый класс
Декомпозиция несколько странная в том плане, что Config - это конфиг, а GameData - это информация, получаемая из конфига, но не есть конфиг, то есть не должна быть его наследником... Это выглядит довольно странным архитектурным решением

2018-05-14 19:42 UTC, SinimaWath commented on utils/logger.h
> +    static void setLoggerDist(const std::string& dist);
Вызывать до создания интерфейса из логгера. То есть поменять куда мы выводим логг, можно только перед созданием Logger. Пока что считаю это оправданным решением, из-за простоты проекта и логгера

2018-05-14 20:29 UTC, SinimaWath commented
Изменил архитектуру с учетом ваших замечаний. Теперь GameData - класс хранящий полученные данный из ConfigExtractor. ConfigExtractor - описывает интерфейс для всех реализаций ( для различных видов конфигов).

2018-05-17 08:49 UTC, leshiy1295 reviewed
выглядит лучше

2018-05-17 08:49 UTC, leshiy1295 commented on utils/gamedata/configextractorlibconfig.h
>  using namespace libconfig;
это стоит спрятать в реализацию

2018-05-17 08:49 UTC, leshiy1295 commented on utils/gamedata/configsingleplayermenudata.h
> +        ConfigExtractorLibconfig(std::move(" Is ConfigSignlePLayerMenuData created "),
хардкод строки

2018-05-18 06:05 UTC, leshiy1295 commented on utils/gamedata/configextractorlibconfig.h
> +#include <libconfig.h++>
попробуйте спрятать libconfig целиком в cpp при помощи PIMPL

2018-06-16 11:07 UTC, leshiy1295 approved these changes
Ок

2018-06-16 11:18 UTC, merged